
#ifndef __MAIN_H__
#define __MAIN_H__

#include<stdio.h>                 
#include<stdlib.h>              
#include<string.h>              
#include"list.h"
#include"config.h"
#include"login.h"
#include"menu.h"
#include"function.h"
#include"controler.h"
#include"print.h"
#include"search.h"
#include"sort.h"
#include<graphics.h>

extern User* login_now;
extern User_List all_user;
extern Record_List all_record;
extern Record_List backup_record;
extern Record_List interval_record ;



#endif 

